"""empty message

Revision ID: 3f4a04d5e786
Revises: d9cae427537d
Create Date: 2020-12-09 22:43:54.815113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4a04d5e786'
down_revision = 'd9cae427537d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'meme', ['name'])
    op.add_column('user', sa.Column('joinDate', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'joinDate')
    op.drop_constraint(None, 'meme', type_='unique')
    # ### end Alembic commands ###
