"""empty message

Revision ID: 4822d2bc2cea
Revises: 3f4a04d5e786
Create Date: 2020-12-09 22:45:39.803820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4822d2bc2cea'
down_revision = '3f4a04d5e786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'meme', ['name'])
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column('user', sa.Column('joinDate', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'joinDate')
    op.drop_constraint(None, 'meme', type_='unique')
    # ### end Alembic commands ###
